# CMake generated Testfile for 
# Source directory: /home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/comm_dynamic_costs
# Build directory: /home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/comm_dynamic_costs
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(smpi_comm-dynamic-cost-thread "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/comm_dynamic_costs" "--setenv" "libdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/lib" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/simple-execute" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/comm_dynamic_costs/comm-dynamic-cost.tesh")
set_tests_properties(smpi_comm-dynamic-cost-thread PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;99;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/comm_dynamic_costs/CMakeLists.txt;10;ADD_TESH_FACTORIES;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/comm_dynamic_costs/CMakeLists.txt;0;")
add_test(smpi_comm-dynamic-cost-boost "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/comm_dynamic_costs" "--setenv" "libdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/lib" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/simple-execute" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/comm_dynamic_costs/comm-dynamic-cost.tesh")
set_tests_properties(smpi_comm-dynamic-cost-boost PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;99;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/comm_dynamic_costs/CMakeLists.txt;10;ADD_TESH_FACTORIES;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/comm_dynamic_costs/CMakeLists.txt;0;")
add_test(smpi_comm-dynamic-cost-raw "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/comm_dynamic_costs" "--setenv" "libdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/lib" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/simple-execute" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/comm_dynamic_costs/comm-dynamic-cost.tesh")
set_tests_properties(smpi_comm-dynamic-cost-raw PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;99;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/comm_dynamic_costs/CMakeLists.txt;10;ADD_TESH_FACTORIES;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/comm_dynamic_costs/CMakeLists.txt;0;")
add_test(smpi_comm-dynamic-cost-ucontext "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/comm_dynamic_costs" "--setenv" "libdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/lib" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/simple-execute" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/comm_dynamic_costs/comm-dynamic-cost.tesh")
set_tests_properties(smpi_comm-dynamic-cost-ucontext PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;99;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/comm_dynamic_costs/CMakeLists.txt;10;ADD_TESH_FACTORIES;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/comm_dynamic_costs/CMakeLists.txt;0;")
