# CMake generated Testfile for 
# Source directory: /home/daniel.rojas/myApps/sources/simgrid-3.32/examples/sthread
# Build directory: /home/daniel.rojas/myApps/sources/simgrid-3.32/examples/sthread
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(pthread-mutex-simple-boost "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "libdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/lib" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/sthread" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/sthread/pthread-mutex-simple.tesh")
set_tests_properties(pthread-mutex-simple-boost PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;99;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/sthread/CMakeLists.txt;17;ADD_TESH_FACTORIES;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/sthread/CMakeLists.txt;0;")
add_test(pthread-mutex-simple-raw "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "libdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/lib" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/sthread" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/sthread/pthread-mutex-simple.tesh")
set_tests_properties(pthread-mutex-simple-raw PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;99;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/sthread/CMakeLists.txt;17;ADD_TESH_FACTORIES;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/sthread/CMakeLists.txt;0;")
add_test(pthread-mutex-simple-ucontext "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "libdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/lib" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/sthread" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/sthread/pthread-mutex-simple.tesh")
set_tests_properties(pthread-mutex-simple-ucontext PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;99;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/sthread/CMakeLists.txt;17;ADD_TESH_FACTORIES;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/sthread/CMakeLists.txt;0;")
