# CMake generated Testfile for 
# Source directory: /home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel
# Build directory: /home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(stack-overflow-boost "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/stack-overflow" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/stack-overflow" "stack-overflow.tesh")
set_tests_properties(stack-overflow-boost PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;99;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/CMakeLists.txt;14;ADD_TESH_FACTORIES;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/CMakeLists.txt;0;")
add_test(stack-overflow-raw "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/stack-overflow" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/stack-overflow" "stack-overflow.tesh")
set_tests_properties(stack-overflow-raw PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;99;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/CMakeLists.txt;14;ADD_TESH_FACTORIES;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/CMakeLists.txt;0;")
add_test(stack-overflow-ucontext "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/stack-overflow" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/stack-overflow" "stack-overflow.tesh")
set_tests_properties(stack-overflow-ucontext PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;99;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/CMakeLists.txt;14;ADD_TESH_FACTORIES;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/CMakeLists.txt;0;")
add_test(tesh-kernel-context-default "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/context-defaults" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/context-defaults" "factory_raw.tesh")
set_tests_properties(tesh-kernel-context-default PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/CMakeLists.txt;26;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/CMakeLists.txt;0;")
add_test(tesh-kernel-factory-raw "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/context-defaults" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/context-defaults" "factory_raw.tesh")
set_tests_properties(tesh-kernel-factory-raw PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/CMakeLists.txt;39;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/CMakeLists.txt;0;")
add_test(tesh-kernel-factory-thread "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/context-defaults" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/context-defaults" "factory_thread.tesh")
set_tests_properties(tesh-kernel-factory-thread PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/CMakeLists.txt;39;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/CMakeLists.txt;0;")
add_test(tesh-kernel-factory-boost "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/context-defaults" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/context-defaults" "factory_boost.tesh")
set_tests_properties(tesh-kernel-factory-boost PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/CMakeLists.txt;39;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/CMakeLists.txt;0;")
add_test(tesh-kernel-factory-ucontext "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/context-defaults" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/context-defaults" "factory_ucontext.tesh")
set_tests_properties(tesh-kernel-factory-ucontext PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/CMakeLists.txt;39;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/kernel/CMakeLists.txt;0;")
