# CMake generated Testfile for 
# Source directory: /home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf
# Build directory: /home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tesh-surf-lmm_usage "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/lmm_usage" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/lmm_usage" "lmm_usage.tesh")
set_tests_properties(tesh-surf-lmm_usage PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/CMakeLists.txt;11;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/CMakeLists.txt;0;")
add_test(tesh-surf-surf_usage "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/surf_usage" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/surf_usage" "surf_usage.tesh")
set_tests_properties(tesh-surf-surf_usage PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/CMakeLists.txt;11;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/CMakeLists.txt;0;")
add_test(tesh-surf-surf_usage2 "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/surf_usage2" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/surf_usage2" "surf_usage2.tesh")
set_tests_properties(tesh-surf-surf_usage2 PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/CMakeLists.txt;11;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/CMakeLists.txt;0;")
add_test(tesh-surf-maxmin-large "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/maxmin_bench" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/maxmin_bench" "maxmin_bench_large.tesh")
set_tests_properties(tesh-surf-maxmin-large PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/CMakeLists.txt;27;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/CMakeLists.txt;0;")
add_test(tesh-surf-maxmin-small "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/maxmin_bench" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/maxmin_bench" "maxmin_bench_small.tesh")
set_tests_properties(tesh-surf-maxmin-small PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/CMakeLists.txt;31;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/CMakeLists.txt;0;")
add_test(tesh-surf-maxmin-medium "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/maxmin_bench" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/maxmin_bench" "maxmin_bench_medium.tesh")
set_tests_properties(tesh-surf-maxmin-medium PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/CMakeLists.txt;31;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/surf/CMakeLists.txt;0;")
