# CMake generated Testfile for 
# Source directory: /home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt
# Build directory: /home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tesh-xbt-cmdline "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/cmdline" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/cmdline" "cmdline.tesh")
set_tests_properties(tesh-xbt-cmdline PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/CMakeLists.txt;36;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/CMakeLists.txt;0;")
add_test(tesh-xbt-log_large "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/log_large" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/log_large" "log_large.tesh")
set_tests_properties(tesh-xbt-log_large PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/CMakeLists.txt;36;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/CMakeLists.txt;0;")
add_test(tesh-xbt-parallel_log_crashtest "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/parallel_log_crashtest" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/parallel_log_crashtest" "parallel_log_crashtest.tesh")
set_tests_properties(tesh-xbt-parallel_log_crashtest PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/CMakeLists.txt;36;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/CMakeLists.txt;0;")
add_test(tesh-xbt-parmap_test "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/parmap_test" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/parmap_test" "parmap_test.tesh")
set_tests_properties(tesh-xbt-parmap_test PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/CMakeLists.txt;36;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/CMakeLists.txt;0;")
add_test(tesh-xbt-signals "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/signals" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/signals" "signals.tesh")
set_tests_properties(tesh-xbt-signals PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/CMakeLists.txt;42;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/CMakeLists.txt;0;")
add_test(tesh-xbt-log "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/log_usage" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/log_usage/log_usage.tesh")
set_tests_properties(tesh-xbt-log PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/CMakeLists.txt;45;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/xbt/CMakeLists.txt;0;")
