# CMake generated Testfile for 
# Source directory: /home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi
# Build directory: /home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(smpi-tracing "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/trace" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/trace" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/trace" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/trace/trace.tesh")
set_tests_properties(smpi-tracing PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;102;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;0;")
add_test(smpi-simple-execute "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/simple-execute" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/simple-execute" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/simple-execute" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/simple-execute/simple-execute.tesh")
set_tests_properties(smpi-simple-execute PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;104;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;0;")
add_test(smpi-simple-execute-cpp-platf "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/simple-execute" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/simple-execute" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--setenv" "libdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/lib" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/simple-execute" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/simple-execute/simple-execute-cpp-platf.tesh")
set_tests_properties(smpi-simple-execute-cpp-platf PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;105;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;0;")
add_test(smpi-tracing-simple "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/trace_simple" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/trace_simple" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/trace_simple" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/trace_simple/trace_simple.tesh")
set_tests_properties(smpi-tracing-simple PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;109;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;0;")
add_test(smpi-tracing-call-location "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/trace_call_location" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/trace_call_location" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/trace_call_location/trace_call_location.tesh")
set_tests_properties(smpi-tracing-call-location PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;110;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;0;")
add_test(smpi-replay "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/replay/replay.tesh")
set_tests_properties(smpi-replay PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;111;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;0;")
add_test(smpi-replay-override-replayer "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/replay/replay-override-replayer.tesh")
set_tests_properties(smpi-replay-override-replayer PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;112;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;0;")
add_test(smpi-gemm "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/gemm" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/gemm" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/gemm" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/gemm/gemm.tesh")
set_tests_properties(smpi-gemm PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;113;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;0;")
add_test(smpi-energy-thread "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:thread" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/energy" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/energy" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/bin" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/energy" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/energy/energy.tesh")
set_tests_properties(smpi-energy-thread PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;99;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;114;ADD_TESH_FACTORIES;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;0;")
add_test(smpi-energy-boost "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:boost" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/energy" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/energy" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/bin" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/energy" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/energy/energy.tesh")
set_tests_properties(smpi-energy-boost PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;99;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;114;ADD_TESH_FACTORIES;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;0;")
add_test(smpi-energy-raw "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:raw" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/energy" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/energy" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/bin" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/energy" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/energy/energy.tesh")
set_tests_properties(smpi-energy-raw PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;99;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;114;ADD_TESH_FACTORIES;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;0;")
add_test(smpi-energy-ucontext "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--cfg" "contexts/factory:ucontext" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/energy" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/energy" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--setenv" "bindir=/home/daniel.rojas/myApps/sources/simgrid-3.32/bin" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/energy" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/energy/energy.tesh")
set_tests_properties(smpi-energy-ucontext PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;99;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;114;ADD_TESH_FACTORIES;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;0;")
add_test(smpi-ampi "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi" "/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/ampi_test/ampi_test.tesh")
set_tests_properties(smpi-ampi PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;116;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/smpi/CMakeLists.txt;0;")
