# CMake generated Testfile for 
# Source directory: /home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models
# Build directory: /home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tesh-model-cloud-sharing "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/cloud-sharing" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/cloud-sharing" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/cloud-sharing/cloud-sharing.tesh")
set_tests_properties(tesh-model-cloud-sharing PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/CMakeLists.txt;19;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/CMakeLists.txt;0;")
add_test(tesh-model-ptask_L07_usage "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/ptask_L07_usage" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/ptask_L07_usage" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/ptask_L07_usage/ptask_L07_usage.tesh")
set_tests_properties(tesh-model-ptask_L07_usage PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/CMakeLists.txt;19;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/CMakeLists.txt;0;")
add_test(tesh-model-wifi_usage "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/wifi_usage" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/wifi_usage" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/wifi_usage/wifi_usage.tesh")
set_tests_properties(tesh-model-wifi_usage PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/CMakeLists.txt;19;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/CMakeLists.txt;0;")
add_test(tesh-model-wifi_usage_decay "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/wifi_usage_decay" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/wifi_usage_decay" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/wifi_usage_decay/wifi_usage_decay.tesh")
set_tests_properties(tesh-model-wifi_usage_decay PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/CMakeLists.txt;19;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/CMakeLists.txt;0;")
add_test(tesh-model-cm02-set-lat-bw "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/cm02-set-lat-bw" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/cm02-set-lat-bw" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/cm02-set-lat-bw/cm02-set-lat-bw.tesh")
set_tests_properties(tesh-model-cm02-set-lat-bw PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/CMakeLists.txt;19;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/CMakeLists.txt;0;")
add_test(tesh-model-issue105 "/usr/bin/python3.6" "/home/daniel.rojas/myApps/sources/simgrid-3.32/bin/tesh" "--ignore-jenkins" "--setenv" "srcdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/issue105" "--setenv" "platfdir=/home/daniel.rojas/myApps/sources/simgrid-3.32/examples/platforms" "--cd" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/issue105" "/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/issue105/issue105.tesh")
set_tests_properties(tesh-model-issue105 PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel.rojas/myApps/sources/simgrid-3.32/tools/cmake/Tests.cmake;49;ADD_TEST;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/CMakeLists.txt;19;ADD_TESH;/home/daniel.rojas/myApps/sources/simgrid-3.32/teshsuite/models/CMakeLists.txt;0;")
